version: "3.1"

services:
  redis_container:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always