version: "3.1"

services:
  redis_prod:
    image: redis:latest
    container_name: redis_1
    ports:
      - 6389:6379
    labels:
      - "name=redis_prod"
      - "mode=standalone"
    restart: always

  redis_test:
    image: redis:latest
    container_name: redis_2
    ports:
      - 6380:6379
    labels:
      - "name=redis_test"
      - "mode=standalone"
    restart: always