version: "3"

volumes:
  esdata:
  product-mysql-01:
  product-mysql-02:
  chromadb:

networks:
  elasticsearch-net:
    driver: bridge
  chroma-net:
    driver: bridge

services:
  redis_prod:
    image: redis:latest
    container_name: redis_1
    ports:
      - 6389:6379
    labels:
      - "name=redis_prod"
      - "mode=standalone"
    restart: always

  redis_test:
    image: redis:latest
    container_name: redis_2
    ports:
      - 6380:6379
    labels:
      - "name=redis_test"
      - "mode=standalone"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment:
      - URLS_PRIMARY_NAME=chameleon
      - "URLS=[ 
                { url: 'http://localhost:8081/docs/account-api.yaml', name: 'account' },
                { url: 'http://localhost:8082/docs/product-api.yaml', name: 'product' },
            ]"
    ports:
      - "7963:8080"

  product-mysql-01:
    container_name: product-mysql-01
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - product-mysql-01:/var/lib/mysql
      - ./product/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: product
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  product-mysql-02:
    container_name: product-mysql-02
    image: mysql
    ports:
      - 13307:3306
    volumes:
      - product-mysql-02:/var/lib/mysql
      - ./product/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: product
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=1234
    ports:
      - "9200:9200"
    networks:
      - elasticsearch-net
    volumes:
      - esdata:/usr/share/elasticsearch/data

  chroma:
    container_name: chroma-db
    image: chromadb/chroma:latest
    volumes:
      - chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - chroma-net
